"""Add funds and fund closes

Revision ID: 1f044df0b400
Revises: e0b8a35143c0
Create Date: 2026-08-19 21:46:09.439966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f044df0b400'
down_revision = 'e0b8a35143c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(length=300), nullable=True),
    sa.Column('geography', sa.String(length=200), nullable=True),
    sa.Column('vintage_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fund_close',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('close_type', sa.String(length=50), nullable=True),
    sa.Column('announced_at', sa.DateTime(), nullable=True),
    sa.Column('event_evidence', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['fund.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fund_close')
    op.drop_table('fund')
    # ### end Alembic commands ###
