"""Add canonical company sector

Revision ID: 1ff55d6d2bdc
Revises: b702c970c39a
Create Date: 2026-08-20 02:46:26.602604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ff55d6d2bdc'
down_revision = 'b702c970c39a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canonical_sector', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('canonical_sector')

    # ### end Alembic commands ###
