"""Add company location metadata

Revision ID: 4dacb5c70e33
Revises: 79f2d66ec3d6
Create Date: 2026-08-19 17:41:48.101053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dacb5c70e33'
down_revision = '79f2d66ec3d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('founded_year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('founded_year')
        batch_op.drop_column('country')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
