"""add multi-source fund close evidence

Revision ID: 6dda0fc9649c
Revises: 87538e96676c
Create Date: 2026-08-20 15:01:12.168115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dda0fc9649c'
down_revision = '87538e96676c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_close_articles',
    sa.Column('fund_close_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['fund_close_id'], ['fund_close.id'], ),
    sa.PrimaryKeyConstraint('fund_close_id', 'article_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fund_close_articles')
    # ### end Alembic commands ###
