"""add extraction records

Revision ID: 8733b6753aa4
Revises: a9b19bb833db
Create Date: 2026-08-21 13:35:31.400922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8733b6753aa4'
down_revision = 'a9b19bb833db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('extractor_version', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('validation_state', sa.String(length=30), nullable=False),
    sa.Column('validation_flags', sa.JSON(), nullable=False),
    sa.Column('validator_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('promoted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extraction_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extraction_record_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_record_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_record_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_record_extractor_version'), ['extractor_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_record_validation_state'), ['validation_state'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extraction_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extraction_record_validation_state'))
        batch_op.drop_index(batch_op.f('ix_extraction_record_extractor_version'))
        batch_op.drop_index(batch_op.f('ix_extraction_record_event_type'))
        batch_op.drop_index(batch_op.f('ix_extraction_record_created_at'))
        batch_op.drop_index(batch_op.f('ix_extraction_record_article_id'))

    op.drop_table('extraction_record')
    # ### end Alembic commands ###
