"""scope entity alias uniqueness by entity type

Revision ID: 8fcd8775ad06
Revises: e1fe52ccb576
Create Date: 2026-08-20 03:44:18.643446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fcd8775ad06'
down_revision = 'e1fe52ccb576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity_alias', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_entity_alias_type_alias', ['entity_type', 'alias'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity_alias', schema=None) as batch_op:
        batch_op.drop_constraint('uq_entity_alias_type_alias', type_='unique')

    # ### end Alembic commands ###
