"""Add source run operations

Revision ID: a9b19bb833db
Revises: f0e9d0f01279
Create Date: 2026-08-20 19:46:18.949954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b19bb833db'
down_revision = 'f0e9d0f01279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=100), nullable=False),
    sa.Column('source_name', sa.String(length=150), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('process_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('articles_discovered', sa.Integer(), nullable=False),
    sa.Column('articles_relevant', sa.Integer(), nullable=False),
    sa.Column('articles_saved', sa.Integer(), nullable=False),
    sa.Column('dates_populated', sa.Integer(), nullable=False),
    sa.Column('remaining_undated', sa.Integer(), nullable=True),
    sa.Column('articles_selected', sa.Integer(), nullable=False),
    sa.Column('stale_articles_skipped', sa.Integer(), nullable=False),
    sa.Column('compound_articles_skipped', sa.Integer(), nullable=False),
    sa.Column('content_retrieved', sa.Integer(), nullable=False),
    sa.Column('content_failed', sa.Integer(), nullable=False),
    sa.Column('funding_processed', sa.Integer(), nullable=False),
    sa.Column('funding_rounds', sa.Integer(), nullable=False),
    sa.Column('fund_news_processed', sa.Integer(), nullable=False),
    sa.Column('fund_closes', sa.Integer(), nullable=False),
    sa.Column('processing_failed', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_run_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_run_source_key'), ['source_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_run_source_name'), ['source_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_run_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_run_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_run_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_run_status'))
        batch_op.drop_index(batch_op.f('ix_source_run_started_at'))
        batch_op.drop_index(batch_op.f('ix_source_run_source_type'))
        batch_op.drop_index(batch_op.f('ix_source_run_source_name'))
        batch_op.drop_index(batch_op.f('ix_source_run_source_key'))
        batch_op.drop_index(batch_op.f('ix_source_run_mode'))

    op.drop_table('source_run')
    # ### end Alembic commands ###
