"""Add multi-source funding event evidence

Revision ID: b702c970c39a
Revises: 1f044df0b400
Create Date: 2026-08-19 23:07:57.958653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b702c970c39a'
down_revision = '1f044df0b400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funding_round_articles',
    sa.Column('funding_round_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['funding_round_id'], ['funding_round.id'], ),
    sa.PrimaryKeyConstraint('funding_round_id', 'article_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funding_round_articles')
    # ### end Alembic commands ###
