"""Add funding event evidence

Revision ID: d3eca8401187
Revises: 99d8e5e90f52
Create Date: 2026-08-19 18:09:31.565585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3eca8401187'
down_revision = '99d8e5e90f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funding_round', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_evidence', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funding_round', schema=None) as batch_op:
        batch_op.drop_column('event_evidence')

    # ### end Alembic commands ###
