"""Add LLM processing state to articles

Revision ID: db57bcbd9325
Revises: d3eca8401187
Create Date: 2026-08-19 18:16:18.372817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db57bcbd9325'
down_revision = 'd3eca8401187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_processed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('llm_is_funding_round', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('llm_is_funding_round')
        batch_op.drop_column('llm_processed_at')

    # ### end Alembic commands ###
