"""Add canonical funding round type

Revision ID: e1fe52ccb576
Revises: 1ff55d6d2bdc
Create Date: 2026-08-20 02:57:54.235543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1fe52ccb576'
down_revision = '1ff55d6d2bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funding_round', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canonical_round_type', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funding_round', schema=None) as batch_op:
        batch_op.drop_column('canonical_round_type')

    # ### end Alembic commands ###
