"""add evidence source provenance

Revision ID: f0e9d0f01279
Revises: 6dda0fc9649c
Create Date: 2026-08-20 15:09:01.675681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e9d0f01279'
down_revision = '6dda0fc9649c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('discovery_method', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('discovery_method')
        batch_op.drop_column('source_type')

    # ### end Alembic commands ###
